import pygetwindow as gw
print('\n - \n')
print("gw.getAllTitles()")
print('\n  \n')
print(gw.getAllTitles())
print('\n - \n')
print("gw.getAllWindows()")
print('\n  \n')
print(gw.getAllWindows())
print('\n - \n')
print("gw.getWindowsWithTitle('Untitled')")
print('\n  \n')
print(gw.getWindowsWithTitle('Untitled'))
print('\n - \n')
print("gw.getActiveWindow()")
print('\n  \n')
print(gw.getActiveWindow())
print('\n - \n')
print("gw.getActiveWindow().title")
print('\n  \n')
print(gw.getActiveWindow().title)
print('\n - \n')
print("gw.getWindowsAt(10, 10)")
print('\n  \n')
print(gw.getWindowsAt(10, 10))
print('\n - \n')
